### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by moh1122** [quasoft/backgammonjs#1]
Hello nice git
can you please tell us how to install it?
Thank you

**Comment by quasoft** [comment]
Hello,

Its still under progress and not installable yet.

Should have written that in the Readme.

But anyone who wants to help finish the project is welcome.

**Comment by quasoft** [comment]
Update: The game is now both installable and playable. 

It's in alpha state as some features are still missing.

Install instructions and link to demo can be found in project README.
